name: portfolio-ko

services:
  portfolio-ko:
    container_name: portfolio-ko
    build: ./project
    volumes:
      - ${CONFIG_FILE:-./project/public/config.json}:/usr/share/nginx/html/config.json
      - ${ASSETS_DIR:-./project/public/assets}:/usr/share/nginx/html/assets
    restart: always
